version: '3'

services:
  web:
    build: .
    depends_on:
      - 'postgres'
    environment:
      - 'PORT=3000'
    ports:
      - '3000:3000'
    volumes:
      - '.:/opt/rails'
  postgres:
    image: 'postgres:10'
